# Dennis Audu [148463193]
# daudu@myseneca.ca

CC = g++
LIBS = -L . libPidUtil.a
CFLAGS = -Wall -I.

all: Lab1
Lab1: lab1.cpp
	 $(CC) $(CFLAGS) -o Lab1 lab1.cpp $(LIBS)
	chmod +x Lab1
clean:
	rm -f *.o Lab1
